name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 */3 * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
        # ... other options
         # Coding Habit details
         plugin_lines: yes
         plugin_lines_skipped: repo # List of skipped repositories
         plugin_habits: yes
         plugin_habits_from: 200       # Use 200 events to compute habits
         plugin_habits_days: 30        # Keep only events from last 30 days
         plugin_habits_facts: yes      # Display facts section
         plugin_habits_charts: yes     # Display charts section
         plugin_habits_trim: yes       # Trim unused hours on daily chart
         config_timezone: America/Los_Angeles # Set timezone
         # Contribution full calender
         plugin_isocalendar: yes
         plugin_isocalendar_duration: full-year # Display full year instead of half year
          # Your GitHub token
         token: ${{ secrets.METRICS_TOKEN }}
