name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
         plugin_habits: yes
         plugin_habits_from: 200       # Use 200 events to compute habits
         plugin_habits_days: 14        # Keep only events from last 14 days
         plugin_habits_facts: yes      # Display facts section
         plugin_habits_charts: yes     # Display charts section
         plugin_habits_trim: yes       # Trim unused hours on daily chart
         config_timezone: America/Los_Angeles # Set timezone
         plugin_achievements: yes
         plugin_achievements_threshold: B      # Display achievements with rank B or higher
         plugin_achievements_secrets: yes      # Display unlocked secrets achievements
         plugin_achievements_display: compact  # Use compact display
         plugin_achievements_limit: 0          # Display all unlocked achievements (no limit)
         plugin_achievements_ignored: octonaut # Hide "octonaut" achievement
         plugin_achievements_only: explorer    # Display only "explorer" achievement (don't use with "ignored" option)
         plugin_isocalendar: yes
         plugin_isocalendar_duration: full-year # Display full year instead of half year
          # Your GitHub token
         token: ${{ secrets.METRICS_TOKEN }}
