name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 */4 * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
        # ... other options
         # Coding Habit details
         plugin_lines: yes
         plugin_lines_skipped: repo # List of skipped repositories
         # Contribution full calender
         plugin_isocalendar: yes
         plugin_isocalendar_duration: full-year # Display full year instead of half year
          # Your GitHub token
         token: ${{ secrets.METRICS_TOKEN }}
